
# ==========================================
# JPA
# ==========================================
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.format_sql=true

app.testProp=Property of test Updated for Bus and Message Broker 5